// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package postgresRepo

import (
	"database/sql"
)

type Image struct {
	ID         int32        `json:"id"`
	UserEmail  string       `json:"user_email"`
	ImageUrl   string       `json:"image_url"`
	UploadedAt sql.NullTime `json:"uploaded_at"`
}

type User struct {
	ID        int32        `json:"id"`
	Name      string       `json:"name"`
	Username  string       `json:"username"`
	Email     string       `json:"email"`
	Password  string       `json:"password"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}
